#ifndef WS_CONSTANTS_H
#define WS_CONSTANTS_H

#define WSC_MAX_LABEL_LENGTH 256

#define WSC_READ_BUFFER_SIZE 256
#define WSC_HEAP_PAGE_SIZE   64

#define WSC_INIT_INSTR_CAP 16
#define WSC_INIT_LABEL_CAP 16
#define WSC_INIT_DATA_CAP  16
#define WSC_INIT_CALL_CAP  16
#define WSC_INIT_PAGE_CAP  1

#endif /* WS_CONSTANTS_H */